In [102]:
import emcee
import numpy as np
import corner 
%pylab inline
import matplotlib.pyplot as plt
%matplotlib inline
from tqdm.notebook import tqdm as tqdm

Populating the interactive namespace from numpy and matplotlib


In [103]:
#Metropolis Algorithm
def iteration(lattice, T, N, dim=2):
    loc = np.random.randint(0, high=N, size=dim, dtype=int)
    si = lattice[tuple(loc)]
    sj = []
    
    for i in range(dim):
        left = loc
        right = loc
        left[i] = left[i]-1
        right[i] = right[i]+1
        s1 = lattice[tuple(left)]
        s2 = lattice[tuple(right)]
        sj.append(s1)
        sj.append(s2)
    del_e = np.sum(2*si*np.asarray(sj))    
    
    if del_e <= 0:
        return lattice
    
    prob = np.exp(-del_e / T)
    p = [prob, 1-prob]
    flip = np.random.choice([1, 0], replace = True, p = p)
    
    if flip == 1:
        lattice[tuple(loc)] = -lattice[tuple(loc)]
        return lattice
    
    return lattice

def MCMC(chain_len, T, N, dim=2, burn_in=100):
    if burn_in > chain_len:
        raise Exception("Chain length must be larger than burn_in length")
        
    shape = tuple(N * np.ones(dim, dtype=int))
    lattice = 2*np.random.randint(low=0, high=2, size=shape, dtype=int)-1
    out = []
    
    for i in tqdm(range(chain_len)):
        lattice = iteration(lattice, T, N, dim)
        if i < burn_in:
            continue
        out.append(lattice)
    return out
        
#Specifiying Conditions
N=1000
T=2.3
chain_length = 100*N
run_1 = MCMC(chain_length, T, N)

  0%|          | 0/100000 [00:00<?, ?it/s]

In [94]:
print(run_1[99])

[[ 1  1  1 ...  1 -1 -1]
 [-1 -1  1 ... -1 -1 -1]
 [-1  1  1 ...  1 -1 -1]
 ...
 [-1  1 -1 ...  1 -1 -1]
 [-1 -1  1 ...  1 -1 -1]
 [ 1 -1  1 ... -1 -1  1]]
